apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
      #   tags.datadoghq.com/env: "production"
      #   tags.datadoghq.com/service: "my-frontend-app"
      #   tags.datadoghq.com/version: "v1.9.3"
      # annotations:
      #   ad.datadoghq.com/frontend.check_names: '["app-metrics"]'
      #   ad.datadoghq.com/frontend.init_configs: '[{}]'
      #   ad.datadoghq.com/frontend.instances: |
      #     [
      #       {
      #         "prometheus_url": "http://frontend-service:80/metrics",
      #         "namespace": "mvc_kubernetes",
      #         "metrics": [ {"dotnet_total_memory_bytes": "prometheus.dotnet.total.memory.bytes"}]
      #       }
      #     ]
    spec:
      containers:
      - name: frontend
        image: aaacr.azurecr.io/web-app:1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: "100Mi"
          requests:
            cpu: 100m
            memory: "50Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
